/**
 * IMUNIVIDA MVP v2.0
 * Architecture: Modular Class-Based
 * Author: Generated by AI Architect
 */

// --- 1. DATA & STORAGE SERVICE (Simulando Backend) ---
class StorageService {
    constructor() {
        this.KEY_DEPENDENTS = 'imuni_dependents_v2';
        this.KEY_USER = 'imuni_user_v2';
        
        // Inicializa dados mock se vazio
        if (!localStorage.getItem(this.KEY_DEPENDENTS)) {
            this.saveDependents([
                { id: 1, name: 'João Silva', dob: '2019-05-20', vaccines: 'late' },
                { id: 2, name: 'Ana Silva', dob: '2021-11-10', vaccines: 'ok' }
            ]);
        }
        
        if(!localStorage.getItem(this.KEY_USER)) {
            this.saveUser({ points: 350, badges: ['welcome'] });
        }
    }

    getDependents() { return JSON.parse(localStorage.getItem(this.KEY_DEPENDENTS)); }
    
    saveDependents(data) { localStorage.setItem(this.KEY_DEPENDENTS, JSON.stringify(data)); }

    getUser() { return JSON.parse(localStorage.getItem(this.KEY_USER)); }

    updatePoints(amount) {
        const user = this.getUser();
        user.points += amount;
        localStorage.setItem(this.KEY_USER, JSON.stringify(user));
        return user.points;
    }
}

// --- 2. UI CONTROLLER (Manipulação visual) ---
class UIController {
    constructor() {
        this.pages = document.querySelectorAll('.page');
        this.tabBar = document.getElementById('main-tab-bar');
        this.toastEl = document.getElementById('toast');
        this.simulator = document.querySelector('.iphone-chassis');
    }

    showPage(pageId) {
        // 1. Oculta todas
        this.pages.forEach(p => p.classList.remove('active'));
        
        // 2. Mostra alvo
        const target = document.getElementById(pageId);
        if(target) target.classList.add('active');

        // 3. Lógica da TabBar e Theme
        const isRoot = ['page-dashboard', 'page-incentives'].includes(pageId);
        const isDark = target.dataset.theme === 'dark';
        
        if (pageId === 'page-homescreen' || pageId === 'page-login') {
            this.tabBar.classList.add('hidden');
        } else {
            this.tabBar.classList.remove('hidden');
        }

        // Update Tab Icons
        document.querySelectorAll('.tab-item').forEach(tab => {
            tab.classList.toggle('active', tab.dataset.target === pageId);
        });

        // Update Theme (Status Bar)
        target.parentElement.parentElement.parentElement.setAttribute('data-theme', isDark ? 'dark' : 'light');
    }

    showToast(msg, type = 'success') {
        const icon = this.toastEl.querySelector('#toast-icon');
        const text = this.toastEl.querySelector('#toast-msg');
        
        text.textContent = msg;
        icon.textContent = type === 'success' ? 'check_circle' : 'error';
        this.toastEl.style.backgroundColor = type === 'success' ? 'rgba(0,0,0,0.8)' : 'rgba(255, 59, 48, 0.9)';

        this.toastEl.classList.remove('toast-hidden');
        this.toastEl.classList.add('toast-visible');

        setTimeout(() => {
            this.toastEl.classList.remove('toast-visible');
            this.toastEl.classList.add('toast-hidden');
        }, 3000);
    }
    
    // Efeito 3D no Mouse (Desktop Only)
    init3DEffect() {
        document.addEventListener('mousemove', (e) => {
            const x = (window.innerWidth / 2 - e.pageX) / 25;
            const y = (window.innerHeight / 2 - e.pageY) / 25;
            this.simulator.style.transform = `rotateY(${x}deg) rotateX(${y}deg)`;
        });
    }
}

// --- 3. APP LOGIC (O Cérebro) ---
class ImuniApp {
    constructor() {
        this.storage = new StorageService();
        this.ui = new UIController();
        this.history = []; // Pilha de navegação
        
        this.initEvents();
        this.ui.init3DEffect();
        this.renderDashboard();
        
        // Start Screen
        this.navigateTo('page-homescreen');
    }

    navigateTo(pageId) {
        this.history.push(pageId);
        this.ui.showPage(pageId);
        
        if(pageId === 'page-dashboard') this.renderDashboard();
        if(pageId === 'page-incentives') this.renderIncentives();
    }

    goBack() {
        if (this.history.length > 1) {
            this.history.pop(); // Tira atual
            const prev = this.history[this.history.length - 1];
            this.ui.showPage(prev);
        }
    }

    initEvents() {
        // 1. Navegação Global (Delegation)
        document.body.addEventListener('click', (e) => {
            // Botões de Navegação
            const navBtn = e.target.closest('.action-navigate, .tab-item');
            if (navBtn) {
                const target = navBtn.dataset.target;
                this.navigateTo(target);
            }

            // Botão Voltar
            if (e.target.closest('.action-back')) {
                this.goBack();
            }

            // Login Fake
            if (e.target.closest('.action-login')) {
                const btn = e.target.closest('.action-login');
                btn.innerHTML = '<span class="material-symbols-rounded">sync</span> Autenticando...';
                setTimeout(() => {
                    this.navigateTo('page-dashboard');
                    this.ui.showToast('Login Gov.br realizado com sucesso!');
                    btn.innerHTML = '<span class="material-symbols-rounded">account_balance</span> Entrar com Gov.br';
                }, 1500);
            }

            // Resgate Pontos
            if (e.target.closest('.action-redeem')) {
                this.handleRedeem(e.target.closest('.action-redeem'));
            }
        });

        // 2. Formulário Dependente
        document.getElementById('form-dependent').addEventListener('submit', (e) => {
            e.preventDefault();
            const name = document.getElementById('dep-name').value;
            const dob = document.getElementById('dep-dob').value;

            const deps = this.storage.getDependents();
            deps.push({ id: Date.now(), name, dob, vaccines: 'ok' });
            this.storage.saveDependents(deps);

            this.ui.showToast('Dependente cadastrado!');
            this.goBack();
        });
    }

    // Renders
    renderDashboard() {
        const list = document.getElementById('dependents-list');
        const deps = this.storage.getDependents();
        
        list.innerHTML = deps.map(dep => `
            <div class="list-item action-navigate" data-target="page-calendar-detail">
                <div class="user-info">
                    <img src="${dep.name.includes('João') ? 'assets/boyperfil.png' : 'assets/girlperfil.png'}" 
                         class="avatar-profile" 
                         onerror="this.src='https://ui-avatars.com/api/?name=${dep.name}'">
                    <div>
                        <strong>${dep.name}</strong>
                        <div style="font-size: 12px; color: #888">Próx: Meningocócica C</div>
                    </div>
                </div>
                <span class="badge-status ${dep.vaccines === 'late' ? 'status-late' : 'status-ok'}">
                    ${dep.vaccines === 'late' ? 'ATRASADA' : 'EM DIA'}
                </span>
            </div>
        `).join('');
    }

    renderIncentives() {
        const user = this.storage.getUser();
        document.getElementById('user-points').textContent = user.points;
        
        // Controla botões
        document.querySelectorAll('.reward-card').forEach(card => {
            const cost = parseInt(card.dataset.cost);
            if (user.points < cost) {
                card.classList.add('disabled');
                card.querySelector('button').disabled = true;
                card.querySelector('button').textContent = 'Pontos Insuficientes';
            } else {
                card.classList.remove('disabled');
                card.querySelector('button').disabled = false;
            }
        });
    }

    handleRedeem(btn) {
        const card = btn.closest('.reward-card');
        const cost = parseInt(card.dataset.cost);
        const user = this.storage.getUser();

        if (user.points >= cost) {
            this.storage.updatePoints(-cost);
            this.renderIncentives();
            this.ui.showToast('Resgate realizado! Código enviado.');
        }
    }
}

// Inicializa o App
document.addEventListener('DOMContentLoaded', () => {
    window.app = new ImuniApp();
});
